[BUGSExamples]
git-tree-sha1 = "a2175cf46718c25775551803503ecdad7092be67"
lazy = true

    [[BUGSExamples.download]]
    sha256 = "85aaadacab7cdfa5e50a0d0393128e5ea5051db6fdbd3af0f1fadeaf8419f20a"
    url = "https://github.com/TuringLang/JuliaBUGS.jl/releases/download/BUGSExamples-a2175cf46718/BUGSExamples.tar.gz"
