#!/usr/bin/env python3
"""
Stan model generated by DoodleBUGS
Run with CmdStanPy: pip install cmdstanpy
"""
import json
import os
import cmdstanpy

model_code = """
data {
  int<lower=1> N;
  int<lower=1> T;
  real xbar;
  array[T] real x;
  array[N, T] real Y;
}

parameters {
  real<lower=0> tau_c;
  real alpha_c;
  real<lower=0> alpha_tau;
  real beta_c;
  real<lower=0> beta_tau;
  array[N] real alpha;
  array[N] real beta;
}

transformed parameters {
  real sigma;
  real alpha0;
  array[N, T] real mu;
  for (i in 1:N) {
    for (j in 1:T) {
      mu[i,j] = alpha[i] + beta[i] * (x[j] - xbar);
    }
  }
  sigma = 1 / sqrt(tau_c);
  alpha0 = alpha_c - xbar * beta_c;
}

model {
  for (i in 1:N) {
    for (j in 1:T) {
      Y[i,j] ~ normal(mu[i,j], 1.0 / sqrt(tau_c));
    }
    alpha[i] ~ normal(alpha_c, 1.0 / sqrt(alpha_tau));
    beta[i] ~ normal(beta_c, 1.0 / sqrt(beta_tau));
  }
  tau_c ~ gamma(0.001, 0.001);
  alpha_c ~ normal(0.0, 1.0 / sqrt(1.0E-6));
  alpha_tau ~ gamma(0.001, 0.001);
  beta_c ~ normal(0.0, 1.0 / sqrt(1.0E-6));
  beta_tau ~ gamma(0.001, 0.001);
}
"""

data = json.loads("""
{
  "N": 30,
  "T": 5,
  "x": [
    8,
    15,
    22,
    29,
    36
  ],
  "xbar": 22,
  "Y": [
    [
      151,
      199,
      246,
      283,
      320
    ],
    [
      145,
      199,
      249,
      293,
      354
    ],
    [
      147,
      214,
      263,
      312,
      328
    ],
    [
      155,
      200,
      237,
      272,
      297
    ],
    [
      135,
      188,
      230,
      280,
      323
    ],
    [
      159,
      210,
      252,
      298,
      331
    ],
    [
      141,
      189,
      231,
      275,
      305
    ],
    [
      159,
      201,
      248,
      297,
      338
    ],
    [
      177,
      236,
      285,
      350,
      376
    ],
    [
      134,
      182,
      220,
      260,
      296
    ],
    [
      160,
      208,
      261,
      313,
      352
    ],
    [
      143,
      188,
      220,
      273,
      314
    ],
    [
      154,
      200,
      244,
      289,
      325
    ],
    [
      171,
      221,
      270,
      326,
      358
    ],
    [
      163,
      216,
      242,
      281,
      312
    ],
    [
      160,
      207,
      248,
      288,
      324
    ],
    [
      142,
      187,
      234,
      280,
      316
    ],
    [
      156,
      203,
      243,
      283,
      317
    ],
    [
      157,
      212,
      259,
      307,
      336
    ],
    [
      152,
      203,
      246,
      286,
      321
    ],
    [
      154,
      205,
      253,
      298,
      334
    ],
    [
      139,
      190,
      225,
      267,
      302
    ],
    [
      146,
      191,
      229,
      272,
      302
    ],
    [
      157,
      211,
      250,
      285,
      323
    ],
    [
      132,
      185,
      237,
      286,
      331
    ],
    [
      160,
      207,
      257,
      303,
      345
    ],
    [
      169,
      216,
      261,
      295,
      333
    ],
    [
      157,
      205,
      248,
      289,
      316
    ],
    [
      137,
      180,
      219,
      258,
      291
    ],
    [
      153,
      200,
      244,
      286,
      324
    ]
  ]
}
""")

inits = json.loads("""
{
  "alpha": [
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250,
    250
  ],
  "beta": [
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6
  ],
  "alpha_c": 150,
  "beta_c": 10,
  "tau_c": 1,
  "alpha_tau": 1,
  "beta_tau": 1
}
""")

model_dir = os.path.join(os.path.dirname(__file__), "stan_model")
os.makedirs(model_dir, exist_ok=True)

model_file = os.path.join(model_dir, "model.stan")
with open(model_file, "w") as f:
    f.write(model_code)

data_file = os.path.join(model_dir, "data.json")
with open(data_file, "w") as f:
    json.dump(data, f)

inits_file = os.path.join(model_dir, "inits.json")
with open(inits_file, "w") as f:
    json.dump(inits, f)

model = cmdstanpy.CmdStanModel(stan_file=model_file)
fit = model.sample(
    data=data_file,
    inits=inits_file,
    chains=1,
    iter_warmup=1000,
    iter_sampling=1000,
    seed=12345,
)

print(fit.summary())
print(fit.diagnose())
