name: BUGSExamples Documentation

on:
  push:
    branches:
      - main
    tags: '*'
    paths:
      - 'BUGSExamples/**'
      - '.github/workflows/BUGSExamplesDocs.yml'
  pull_request:
    paths:
      - 'BUGSExamples/**'
      - '.github/workflows/BUGSExamplesDocs.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy BUGSExamples docs
        uses: TuringLang/actions/DocsDocumenter@main
        with:
          pkg_path: BUGSExamples
          doc-path: BUGSExamples/docs
          doc-make-path: BUGSExamples/docs/make.jl
          doc-build-path: BUGSExamples/docs/build
          dirname: BUGSExamples
          tag_prefix: "BUGSExamples-"
          use-vitepress: 'true'
