name: Coverage

on:
  push:
    branches:
      - main
    paths:
      - 'JuliaBUGS/**'
      - '.github/workflows/Coverage.yml'
  pull_request:
    paths:
      - 'JuliaBUGS/**'
      - '.github/workflows/Coverage.yml'
  workflow_dispatch:

jobs:
  coverage:
    name: Code Coverage - Julia ${{ matrix.version }} on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64

    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.julia
            ~/.julia/artifacts
          key: ${{ runner.os }}-julia-${{ matrix.version }}-${{ matrix.arch }}-${{ hashFiles('JuliaBUGS/Project.toml', 'JuliaBUGS/Manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-${{ matrix.version }}-${{ matrix.arch }}-
            ${{ runner.os }}-julia-${{ matrix.version }}-
      
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: JuliaBUGS

      - name: Running all tests with coverage
        uses: julia-actions/julia-runtest@v1
        with:
          project: JuliaBUGS
        env:
          TEST_GROUP: "all"

      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: JuliaBUGS/src,JuliaBUGS/ext

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          
      - uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info